# Generated by Django 5.2.17 on 2026-09-16 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_yearly_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_yearly_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_corrections', to=settings.AUTH_USER_MODEL)),
                ('salary_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='salary.salaryperiod')),
            ],
        ),
    ]
