# Generated by Django 5.2.17 on 2026-09-16 07:23

import common.constraints
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_enable_btree_gist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_periods', to='employees.employee')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='employment_period_end_after_start'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('employee',), name='one_open_employment_period_per_employee'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('employee', '='), (common.constraints.DateRangeFunc('effective_from', 'effective_to', models.Value('[)')), '&&')], name='no_overlapping_employment_period')],
            },
        ),
    ]
